FROM php:8.4-apache

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
RUN sed -ri -e 's!AllowOverride None!AllowOverride All!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
RUN apt-get update && apt-get install -y libsqlite3-dev libxml2-dev
RUN docker-php-ext-install pdo_sqlite xml pdo_mysql
# RUN apt-get update; \
#     apt-get install -y libmagickwand-dev libmagickcore-dev; \
#     pecl install imagick; \
#     docker-php-ext-enable imagick;
RUN a2enmod rewrite

COPY . /var/www/html/
RUN chown -R www-data:www-data /var/www/html
ENTRYPOINT [ "/bin/bash", "/var/www/html/container-run.sh" ]